<a href="https://colab.research.google.com/github/lankelasharanya04-crypto/datascience_tasks/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import necessary libraries
import numpy as np

Part 1: Creating and Reshaping Arrays
1. Create Arrays:
-  Create two NumPy arrays:
- A 1D array of 10 equally spaced values between 0 and 50.
- A 2D array of shape (3x3) containing random integers
between 5 and 20.
2. Array Dimensions:
-  Print the dimensions of both arrays.
-  Print the shape of both arrays.
3. Reshaping:
-  Reshape the 1D array into a 2D array with shape (2x5).
- Print the reshaped array.
 Flatten the reshaped array back to 1D and print it.

In [2]:
#PART 1

# Array Creation
arr1=np.linspace(0,50,10)
print("Array 1 : ",arr1)
arr2=np.random.randint(5,20,size=9)
arr2=arr2.reshape(3,3)
print("Array 2 : ",arr2)

# Array Dimensions
print("Array 1 dim : ",arr1.ndim)
print("Array 2 dim : ",arr2.ndim)

# Reshaping
arr4=np.array([1,2,3,4,5,6,7,8,9,10])
print("New array created is ",arr4)
arr3=arr4.reshape(2,5)
print("Array after reshaping into 2x5 dimensions : ",arr3)







Array 1 :  [ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
Array 2 :  [[ 7  8  6]
 [15  6 15]
 [12 12 12]]
Array 1 dim :  1
Array 2 dim :  2
New array created is  [ 1  2  3  4  5  6  7  8  9 10]
Array after reshaping into 2x5 dimensions :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Part 2: Indexing and Slicing
4. Indexing:
- For the 2D array created in Part 1, print the element present at the
2nd row and 3rd column.
- Extract the first two rows and the last two columns of the array.
5. Slicing:
- Slice the first four elements from the flattened 1D array.
- Reverse the elements of the 1D array using slicing.

In [3]:

print("--------------------------PART 2-----------------------")
# indexing
print("element present at 2nd row 3rd column for 2d array is ",arr2[1:2,2:3])
print("First two rows  of the array are ", arr2[0:2,:])
print("last two columns of the  array ", arr2[:,1:])

#Slicing
newarr=arr2.reshape(-1)
print("Flattening of 2d array ",newarr)
print("First four elements from the flattened array ",newarr[:4])
print("reverse order of Array using slicing ",newarr[::-1])

--------------------------PART 2-----------------------
element present at 2nd row 3rd column for 2d array is  [[15]]
First two rows  of the array are  [[ 7  8  6]
 [15  6 15]]
last two columns of the  array  [[ 8  6]
 [ 6 15]
 [12 12]]
Flattening of 2d array  [ 7  8  6 15  6 15 12 12 12]
First four elements from the flattened array  [ 7  8  6 15]
reverse order of Array using slicing  [12 12 12 15  6 15  6  8  7]


Part 3: Array Operations
6. Array Arithmetic:
- Create another 1D array of 10 integers between 1 and 10.
- Perform the following element-wise operations between the 1D
arrays created in Part 1 and Part 3:
- Addition
- Multiplication
- Subtract a constant value (e.g., 5) from the array

In [4]:
print("----------------------Array arithmetic-------------")
a=np.arange(1,11)
print("array is :", a)
print("Sum of arrays is : ",a+arr1)
print("Multiplication of arrays is : ", a*arr1)
print("Subtraction of a constant value  with 5 is ",a-5)







----------------------Array arithmetic-------------
array is : [ 1  2  3  4  5  6  7  8  9 10]
Sum of arrays is :  [ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
Multiplication of arrays is :  [  0.          11.11111111  33.33333333  66.66666667 111.11111111
 166.66666667 233.33333333 311.11111111 400.         500.        ]
Subtraction of a constant value  with 5 is  [-4 -3 -2 -1  0  1  2  3  4  5]


Part 4: Random Number Generation and Copying
7. Random Numbers:
- Create a 1D array of 5 random values between 0 and 1.
- Create another 1D array of 5 random values between -1 and 1.

In [5]:
print("--------part 4-------")
rarr=np.random.randint(0,1,5)
print("Random array is ",rarr)

rarr2=np.random.randint(5)
print("Random array 2 is ",rarr2)

--------part 4-------
Random array is  [0 0 0 0 0]
Random array 2 is  2


Part 5: Bonus
8. Challenge Task:
- Write a program that asks the user to input a number (n), and then
generates an n x n array of random integers between 1 and 100.
- Find the sum of all the elements in the array and print the result.

In [7]:
print("---part 5---------")

n=int(input())
arra=np.random.randint(1,100,n*n)
arra=arra.reshape(n,n)
print(arra)
print(np.sum(arra))

---part 5---------
4
[[ 2 15 13  9]
 [87 15 45 57]
 [94 96 69 32]
 [92 66 88 35]]
815
